const GooglePlayCats = [
  { value: 98, label: "Overall" },
  { value: 38, label: "Games" },
  { value: 90, submenu: true, label: "Action" },
  { value: 89, submenu: true, label: "Adventure" },
  { value: 84, submenu: true, label: "Arcade" },
  { value: 92, submenu: true, label: "Board" },
  { value: 83, submenu: true, label: "Card" },
  { value: 86, submenu: true, label: "Casino" },
  { value: 4, submenu: true, label: "Casual" },
  { value: 95, submenu: true, label: "Educational" },
  { value: 94, submenu: true, label: "Music" },
  { value: 85, submenu: true, label: "Puzzle" },
  { value: 6, submenu: true, label: "Racing" },
  { value: 97, submenu: true, label: "Role Playing" },
  { value: 93, submenu: true, label: "Simulation" },
  { value: 99, submenu: true, label: "Sports Games" },
  { value: 96, submenu: true, label: "Strategy" },
  { value: 91, submenu: true, label: "Trivia" },
  { value: 87, submenu: true, label: "Word" },
  { value: 9, label: "Books & Reference" },
  { value: 10, label: "Business" },
  { value: 11, label: "Comics" },
  { value: 12, label: "Communication" },
  { value: 13, label: "Education" },
  { value: 14, label: "Entertainment" },
  { value: 88, label: "Family" },
  { value: 15, label: "Finance" },
  { value: 16, label: "Health & Fitness" },
  { value: 17, label: "Libraries & Demo" },
  { value: 18, label: "Lifestyle" },
  { value: 5, label: "Live Wallpaper" },
  { value: 19, label: "Media & Video" },
  { value: 20, label: "Medical" },
  { value: 21, label: "Music & Audio" },
  { value: 22, label: "News & Magazines" },
  { value: 23, label: "Personalization" },
  { value: 24, label: "Photography" },
  { value: 25, label: "Productivity" },
  { value: 26, label: "Shopping" },
  { value: 27, label: "Social" },
  { value: 28, label: "Sports" },
  { value: 29, label: "Tools" },
  { value: 30, label: "Transportation" },
  { value: 31, label: "Travel & Local" },
  { value: 32, label: "Weather" },
  { value: 8, label: "Widgets" }
]

const iTunesConnectCats = [
  { value: 36, label: "Top Overall" },
  { value: 6014, label: "Games" },
  { value: 7001, submenu: true, label: "Action" },
  { value: 7002, submenu: true, label: "Adventure" },
  { value: 7003, submenu: true, label: "Arcade" },
  { value: 7004, submenu: true, label: "Board" },
  { value: 7005, submenu: true, label: "Card" },
  { value: 7006, submenu: true, label: "Casino" },
  { value: 7007, submenu: true, label: "Dice" },
  { value: 7008, submenu: true, label: "Educational" },
  { value: 7009, submenu: true, label: "Family" },
  { value: 7011, submenu: true, label: "Music" },
  { value: 7012, submenu: true, label: "Puzzle" },
  { value: 7013, submenu: true, label: "Racing" },
  { value: 7014, submenu: true, label: "Role Playing" },
  { value: 7015, submenu: true, label: "Simulation" },
  { value: 7016, submenu: true, label: "Sports" },
  { value: 7017, submenu: true, label: "Strategy" },
  { value: 7018, submenu: true, label: "Trivia" },
  { value: 7019, submenu: true, label: "Word" },
  { value: 6018, label: "Books" },
  { value: 6000, label: "Business" },
  { value: 6022, label: "Catalogs" },
  { value: 6017, label: "Education" },
  { value: 6016, label: "Entertainment" },
  { value: 6015, label: "Finance" },
  { value: 6023, label: "Food & Drink" },
  { value: 6013, label: "Health & Fitness" },
  { value: 6012, label: "Lifestyle" },
  { value: 6020, label: "Medical" },
  { value: 6011, label: "Music" },
  { value: 6010, label: "Navigation" },
  { value: 6009, label: "News" },
  { value: 6021, label: "Newsstand" },
  { value: 13007, submenu: true, label: "Arts and Photography" },
  { value: 13006, submenu: true, label: "Automotive" },
  { value: 13008, submenu: true, label: "Brides & Weddings" },
  { value: 13009, submenu: true, label: "Business & Investing" },
  { value: 13010, submenu: true, label: "Children's Magazines" },
  { value: 13011, submenu: true, label: "Computers & Internet" },
  { value: 13012, submenu: true, label: "Cooking, Food & Drink" },
  { value: 13013, submenu: true, label: "Crafts & Hobbies" },
  { value: 13014, submenu: true, label: "Electronics & Audio" },
  { value: 13015, submenu: true, label: "Entertainment" },
  { value: 13002, submenu: true, label: "Fashion & Style" },
  { value: 13017, submenu: true, label: "Health, Mind & Body" },
  { value: 13018, submenu: true, label: "History" },
  { value: 13003, submenu: true, label: "Home & Garden" },
  { value: 13019, submenu: true, label: "Literary Magazines & Journals" },
  { value: 13020, submenu: true, label: "Men's Interest" },
  { value: 13021, submenu: true, label: "Movies and Music" },
  { value: 13001, submenu: true, label: "News & Politics" },
  { value: 13004, submenu: true, label: "Outdoors & Nature" },
  { value: 13023, submenu: true, label: "Parenting & Family" },
  { value: 13024, submenu: true, label: "Pets" },
  { value: 13025, submenu: true, label: "Professional & Trade" },
  { value: 13026, submenu: true, label: "Regional News" },
  { value: 13027, submenu: true, label: "Science" },
  { value: 13005, submenu: true, label: "Sports & Leisure" },
  { value: 13028, submenu: true, label: "Teens" },
  { value: 13029, submenu: true, label: "Travel & Regional" },
  { value: 13030, submenu: true, label: "Women's Interest" },
  { value: 6008, label: "Photo & Video" },
  { value: 6007, label: "Productivity" },
  { value: 6006, label: "Reference" },
  { value: 6024, label: "Shopping" },
  { value: 6005, label: "Social Networking" },
  { value: 6004, label: "Sports" },
  { value: 6003, label: "Travel" },
  { value: 6002, label: "Utilities" },
  { value: 6001, label: "Weather" }
]

export { GooglePlayCats, iTunesConnectCats }
